language: python
python:
  - "3.6"

notifications:
  email: false

install:
  - ./setup_travis_env.sh

before_script:
  - source path.bash.inc

matrix:
  include:
    - env: lint check
      script: python verify.py --check lint
    
    - env: static check
      script: python verify.py --check mypy
    
    - env: docs
      script: python verify.py --check build-docs
    
    - env: unit tests
      script: pytest --cov=torchgeometry test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
