on: [push, pull_request]

jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.6
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install make -c conda-forge
        pip install -r docs/requirements.txt
        make install
    - name: Build Documentation
      shell: bash -l {0}
      run: make build-docs
