name: Test PyPI package

on:
  schedule:
    - cron:  '0 4 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - name: Checkout kornia
        uses: actions/checkout@v6

      - name: Config Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip install Kornia
        run: pip install kornia

      - name: Check dependencies and kornia version
        run: |
          python -c "import torch;print('Pytorch version: ', torch.__version__)"
          python -c "import kornia;print('Kornia version: ', kornia.__version__)"
