name: tests-cuda

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  tests-cuda:
    container:
      image: nvcr.io/nvidia/pytorch:20.03-py3
      options: --gpus all
    runs-on: [self-hosted, Linux, x64]
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        cuda-version: [9.2, 10.1, 10.2]
        pytorch-channel: [pytorch, pytorch-nightly]
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda dependencies
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install pytorch cudatoolkit=${{ matrix.cuda-version }} -c ${{ matrix.pytorch-channel }}
        pip install -r requirements-dev.txt
        python setup.py install
    - name: Run Tests
      shell: bash -l {0}
      run: pytest -v --device cuda --dtype float32,float64 ./test
